window.APP_BCB_CONFIG = {
  appName: "APP-BCB",
  shortName: "BCB",
  band: "BCB",
  bandName: "Breathless Cover Band",
  version: "APP-BCB v1.0 final sync",
  repoName: "APP-BCB",
  sheetId: "1l_cr7pVu4Y3A2v0HPz_3brCNb1011EHIU3hm6D5a47Q",
  endpointUrl: "https://script.google.com/macros/s/AKfycbx6FfjKaqSvRu9Wc8Ym0yH1y-x4VPryt4J4qVM6EOhRDEhGBGr6RrO51xqaUF36mrD6dg/exec",
  cacheKey: "APP_BCB_MOBILE_CACHE_v1",
  sessionAdminKey: "APP_BCB_ADMIN_KEY_SESSION_v1",
  modules: [
    { id: "panel", label: "Panel", tab: null },
    { id: "crm", label: "CRM", tab: "CRM_GENERAL" },
    { id: "seguimiento", label: "Seguimiento", tab: "CRM_GENERAL" },
    { id: "gmail", label: "Gmail", tab: "RESPUESTAS_GMAIL" },
    { id: "conciertos", label: "Conciertos", tab: "CONCIERTOS" },
    { id: "ensayos", label: "Ensayos", tab: "ENSAYOS" },
    { id: "local", label: "Local / Pagos", tab: "PAGOS_LOCAL" },
    { id: "presupuesto", label: "Presupuesto", tab: null },
    { id: "canciones", label: "Canciones", tab: "REPERTORIO" },
    { id: "setlist", label: "Setlist", tab: "SETLISTS" },
    { id: "dossier", label: "Dossier", tab: "PLANTILLAS_DOSSIER" },
    { id: "plantillas", label: "Plantillas", tab: "RESPUESTAS_GMAIL" },
    { id: "tareas", label: "Tareas", tab: "TAREAS" },
    { id: "exportar", label: "Exportar", tab: null, adminOnly: true }
  ],
  headersByTab: {
    CONFIG: ["Clave", "Valor", "Notas"],
    CRM_GENERAL: ["ID", "Fecha alta", "Origen", "Contacto", "Empresa/Entidad", "Tipo evento", "Estado", "Siguiente paso", "Fecha siguiente paso", "Fecha/ventana evento", "Ciudad/lugar", "Email", "Teléfono/WhatsApp", "Formato probable", "Presupuesto/importe", "Probabilidad", "Responsable", "Último contacto", "Material enviado", "Notas", "Estado administrativo"],
    RESPUESTAS_GMAIL: ["ID", "Tipo", "Asunto", "Mensaje base", "Estado", "Última actualización", "Notas"],
    CONCIERTOS: ["ID", "Estado", "Fecha", "Evento", "Cliente/Entidad", "Lugar", "Ciudad", "Hora montaje", "Hora prueba", "Hora actuación", "Duración", "Formato", "Caché/importe", "Sonido", "Iluminación", "Técnico/contacto", "Pago", "Factura", "Siguiente paso", "Fecha siguiente paso", "Notas"],
    ENSAYOS: ["ID", "Fecha", "Hora inicio", "Hora fin", "Lugar", "Objetivo", "Asistentes", "Repertorio trabajado", "Tareas derivadas", "Estado", "Notas"],
    REPERTORIO: ["ID", "Orden base", "Canción", "Artista/Referencia", "Idioma", "Voz principal", "Duración", "Tempo/Energía", "Tonalidad", "Estado", "Bloque sugerido", "Fuente", "Observaciones"],
    SETLISTS: ["Setlist ID", "Nombre setlist", "Orden", "Canción", "Voz", "Duración", "Bloque/curva", "Estado", "Notas"],
    MIEMBROS: ["ID", "Nombre", "Rol artístico", "Instrumento/voz", "Usuario app", "Admin", "Activo", "Email", "Teléfono", "Notas"],
    TAREAS: ["ID", "Área", "Tarea", "Responsable", "Estado", "Prioridad", "Fecha creación", "Fecha vencimiento", "Relacionado con", "Notas"],
    PLANTILLAS_DOSSIER: ["ID", "Tipo", "Título", "Texto", "CTA", "Estado", "Uso recomendado"],
    CONFIG_GRUPO: ["Campo", "Valor", "Fuente/Notas"],
    PAGOS_LOCAL: ["ID", "Mes", "Concepto", "Importe total", "Moneda", "Participantes", "Pagado por", "Reparto por persona", "Estado", "Fecha vencimiento", "Fecha pago", "Notas"],
    DASHBOARD: ["Indicador", "Valor"],
    LOG_APP_BCB: ["Fecha/hora", "Usuario", "Acción", "Módulo", "Detalle", "Resultado", "Versión", "Origen"]
  },
  tableColumnsByTab: {
    CRM_GENERAL: ["Estado", "Contacto", "Empresa/Entidad", "Tipo evento", "Fecha/ventana evento", "Ciudad/lugar", "Siguiente paso", "Fecha siguiente paso", "Responsable", "Notas"],
    RESPUESTAS_GMAIL: ["Tipo", "Asunto", "Mensaje base", "Estado", "Notas"],
    CONCIERTOS: ["Estado", "Fecha", "Evento", "Cliente/Entidad", "Lugar", "Ciudad", "Hora actuación", "Pago", "Factura", "Siguiente paso"],
    ENSAYOS: ["Fecha", "Hora inicio", "Lugar", "Objetivo", "Asistentes", "Repertorio trabajado", "Estado", "Notas"],
    REPERTORIO: ["Orden base", "Canción", "Artista/Referencia", "Idioma", "Voz principal", "Duración", "Tempo/Energía", "Estado"],
    SETLISTS: ["Nombre setlist", "Orden", "Canción", "Voz", "Duración", "Bloque/curva", "Estado", "Notas"],
    TAREAS: ["Estado", "Prioridad", "Área", "Tarea", "Responsable", "Fecha vencimiento", "Relacionado con", "Notas"],
    PLANTILLAS_DOSSIER: ["Tipo", "Título", "Texto", "CTA", "Estado", "Uso recomendado"],
    PAGOS_LOCAL: ["Mes", "Concepto", "Importe total", "Moneda", "Participantes", "Pagado por", "Reparto por persona", "Estado", "Fecha vencimiento", "Fecha pago"],
    MIEMBROS: ["Nombre", "Rol artístico", "Instrumento/voz", "Usuario app", "Admin", "Activo", "Notas"]
  },
  pipelineStates: [
    "Lead nuevo",
    "Revisado",
    "Cualificando",
    "Propuesta enviada",
    "Seguimiento pendiente",
    "Negociación abierta",
    "Pendiente de confirmación",
    "Confirmado",
    "En coordinación",
    "Ejecutado",
    "Factura pendiente",
    "Cobro pendiente",
    "Cobrado",
    "Perdido",
    "Pausado"
  ],
  commercial: {
    titular: "Covers pop-rock en español e inglés con un directo potente, versátil y pensado para enganchar desde la primera canción.",
    subtitulo: "Una banda adaptable, reconocible y muy disfrutable para eventos, salas y públicos mixtos.",
    descripcion: "Breathless Cover Band es una banda de covers pop-rock en español e inglés con directo potente, repertorio muy conocido y una propuesta dinámica orientada a crear ambiente, conectar con el público y hacer que cada actuación funcione de verdad.",
    cta: "Solicita disponibilidad y condiciones para tu fecha."
  }
};